### PR TITLE
refactor: migrate vital record, vrdr, and canary from mitre gitlab

### PR DESCRIPTION
**Pull request by smacadam**
Migrate development work from gitlab to the github monorepo

### CODE REVIEW

**Comment by whichwit** [comment]
Does it make sense to move `projects/Tools` to the root level, since it is not a .NET project? It can replace `scripts`.

**Comment by smacadam** [comment]
moved scripts from Tools to the root level scripts folder

**Review by whichwit — APPROVED** [review]

**Comment by whichwit** [comment]
Anything else to add before we merge (squash)?

**Comment by smacadam** [comment]
We are all good from our end, thanks! @whichwit

**Pull request merged**
