### PR TITLE
build: canary (next) Dockerfile

### PR DESCRIPTION
**Pull request by whichwit**

### CODE REVIEW

**Comment by whichwit** [comment]
@RobertScalfani Right now this builds the Docker image.

**Review by wswarr — APPROVED** [review]

**Comment by smacadam** [comment]
What are the new instructions for building the docker image locally? Now that there's no Dockerfile in the Canary project, the instructions in the README don't work anymore for building the image locally.

**Comment by RobertScalfani** [comment]
I had to use the command `docker build -f canary.Dockerfile -t canary .` to get the dockerfile to build, but the README provides `docker build -t canary .` as the command to use.

**Comment by smacadam** [comment]
I was able to successfully build the docker image after deleting my old Canary/bin and Canary/obs folders using the command Robi sent, but when I tried to run the image locally using the command below it exited immediately. 
`docker run -d -p 8080:80 --name mycanary canary`

@whichwit do you use a different command to run the container locally?

**Comment by whichwit** [comment]
I made the correction to the ENTRYPOINT of the Dockerfile to run the correct executible.

**Pull request merged**
