### PR TITLE
627 sex plurality set order

### PR DESCRIPTION
**Pull request by ptran265**
Implements Sex, Plurality, Set Order, Plurality Edit Flag. Code was shared between Natality and Fetal Death, except for different Patients (Child versus Decedent Fetus), so I refactored the code into getter and setter methods that could be used for both BirthRecord and FetalDeathRecord.

### CODE REVIEW

**Review by RobertScalfani — COMMENTED** [review]
It does feel weird how these fields are the same as the FetalDeath/Birth equivalents and there's no way to just have "Plurality" or "Set Order" fields in the base class. It seems like it has to be this way because of the `[Property]` with a "Fetus Demographics" `category` for Canary. I'm not sure how that `category` argument of `[Property]` is decided, so maybe it doesn't have to be "Child/Fetus Demographics" in the first place which could allow it to be combined in the base class under a simpler name... This might be a non-issue and I might be missing something else, just figured it was worth bringing up, do you or Sarah have any thoughts?

**Comment by ptran265** [comment]
> It does feel weird how some of these fields are the same as the FetalDeath/Birth equivalents and there's no way to just have "Plurality" or "Set Order" fields in the base class. It seems like it has to be this way because of the `[Property]` with a "Fetus Demographics" `category` for Canary. I'm not sure how that `category` argument of `[Property]` is decided, so maybe it doesn't have to be "Child/Fetus Demographics" in the first place which could allow some of these fields to be combined in the base class under a simpler name with a `category` like "Natal Information" or something... This might be a non-issue and I might be missing something else, just figured it was worth bringing up, do you or Sarah have any thoughts?

Besides the Category argument of [Property], the IGUrl arguments differ as well. I'm not sure what that gets used for, but I don't think they could be combined in the base class?

**Comment by RobertScalfani** [comment]
> > It does feel weird how some of these fields are the same as the FetalDeath/Birth equivalents and there's no way to just have "Plurality" or "Set Order" fields in the base class. It seems like it has to be this way because of the `[Property]` with a "Fetus Demographics" `category` for Canary. I'm not sure how that `category` argument of `[Property]` is decided, so maybe it doesn't have to be "Child/Fetus Demographics" in the first place which could allow some of these fields to be combined in the base class under a simpler name with a `category` like "Natal Information" or something... This might be a non-issue and I might be missing something else, just figured it was worth bringing up, do you or Sarah have any thoughts?
> 
> Besides the Category argument of [Property], the IGUrl arguments differ as well. I'm not sure what that gets used for, but I don't think they could be combined in the base class?

I'm also wondering if the original Plurality IGUrl from the birth field was incorrect, should it be `http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-birth-plurality-of-pregnancy` based on `https://build.fhir.org/ig/HL7/fhir-bfdr/StructureDefinition-Observation-birth-plurality-of-pregnancy.html`?

**Comment by ptran265** [comment]
> https://build.fhir.org/ig/HL7/fhir-bfdr/StructureDefinition-Observation-birth-plurality-of-pregnancy.html

Hmm I remember Saul explaining this to me and Rob, but the Birth Plurality of Pregnancy Observation is "not explicitly mapped to an IJE value and supports encoding plurality as a characteristic of pregnancy (outside of the core BFDR use case)." We almost deprecated it but then decided to reinstate it for general utility, but it is not actually used in the birth or fetal death use cases (rather, Plurality is part of Patient-Decedent Fetus like you mentioned for Set Order)

**Comment by RobertScalfani** [comment]
> 
> Hmm I remember Saul explaining this to me and Rob, but the Birth Plurality of Pregnancy Observation is "not explicitly mapped to an IJE value and supports encoding plurality as a characteristic of pregnancy (outside of the core BFDR use case)." We almost deprecated it but then decided to reinstate it for general utility, but it is not actually used in the birth or fetal death use cases (rather, Plurality is mapped to multipleBirthTotal as part of Patient-Decedent Fetus similar to Set Order like you mentioned)

Sounds good, so then I think that means my comment is a moot point. Sorry about that and thanks for bearing with me!

**Comment by smacadam** [comment]
The changes look good but there are some conflicts, rebase on fetal-death-feature and then should be good to merge

**Review by smacadam — APPROVED** [review]

**Pull request merged**
